# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "55432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
  driver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dataset-processed:/app/dataset-processed
      - ./dataset/schema:/app/dataset/schema
      - ./logs:/app/logs

volumes:
  data:
